#!/bin/bash

# Instruction to execute: sh add_issue_type_qa_testing.sh <jira_domain>
# i.e. $ sh add_issue_type_qa_testing.sh mdi-ap-devsecops-qa
# This is scheme for PRODUCT OWNER
source credentials.properties

main() {
  curl --request PUT \
    --url "https://$1.atlassian.net/rest/api/3/permissionscheme/10001" \
    --user "$jira_username:$jira_token" \
    --header 'Accept: application/json' \
    --header 'Content-Type: application/json' \
    --data '{
	"permissions": [
{
      	"holder": {
	"type": "projectRole",
        "parameter": "10004"
		
	
      	},
	"permission": "ADMINISTER_PROJECTS"
},

{
      	"holder": {
	"type": "projectRole",
        "parameter": "10005"
		
      	},
	"permission": "ADMINISTER_PROJECTS"
},


{
      	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "BROWSE_PROJECTS"
},
{
      	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "BROWSE_PROJECTS"
},

{
      	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "BROWSE_PROJECTS"
},




{
	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "MANAGE_SPRINTS_PERMISSION"

},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "MANAGE_SPRINTS_PERMISSION"

},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "MANAGE_SPRINTS_PERMISSION"

},




{
	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "VIEW_AGGREGATED_DATA"
},
{
	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "VIEW_AGGREGATED_DATA"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "VIEW_DEV_TOOLS"

},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "VIEW_DEV_TOOLS"

},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "VIEW_READONLY_WORKFLOW"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "VIEW_READONLY_WORKFLOW"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "ASSIGNABLE_USER"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "ASSIGNABLE_USER"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "ASSIGNABLE_USER"
},



{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "ASSIGN_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "ASSIGN_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "ASSIGN_ISSUES"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "CLOSE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "CLOSE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "CLOSE_ISSUES"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "CREATE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "CREATE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "CREATE_ISSUES"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "DELETE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "DELETE_ISSUES"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "EDIT_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "EDIT_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "EDIT_ISSUES"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "LINK_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "LINK_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "LINK_ISSUES"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "MODIFY_REPORTER"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "MODIFY_REPORTER"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "MODIFY_REPORTER"
},




{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "MOVE_ISSUES"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "MOVE_ISSUES"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "MOVE_ISSUES"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "RESOLVE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "SCHEDULE_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "SET_ISSUE_SECURITY"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "LINK_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "TRANSITION_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "LINK_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "LINK_ISSUES"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "MANAGE_WATCHERS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "MANAGE_WATCHERS"
},

{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},	
	"permission": "VIEW_VOTERS_AND_WATCHERS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},	
	"permission": "VIEW_VOTERS_AND_WATCHERS"
},
{


	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "ADD_COMMENTS"
},
{


	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "ADD_COMMENTS"
},
{


	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "ADD_COMMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_ALL_COMMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_OWN_COMMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "EDIT_ALL_COMMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "EDIT_OWN_COMMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "CREATE_ATTACHMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "CREATE_ATTACHMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "CREATE_ATTACHMENTS"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_ALL_ATTACHMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "DELETE_ALL_ATTACHMENTS"
},
{


	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_OWN_ATTACHMENTS"
},
{


	"holder": {
	"type": "projectRole",
        "parameter": "10005"
	
      	},
	"permission": "DELETE_OWN_ATTACHMENTS"
},
{


	"holder": {
	"type": "projectRole",
        "parameter": "10006"
	
      	},
	"permission": "DELETE_OWN_ATTACHMENTS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_ALL_WORKLOGS"
},


{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "DELETE_OWN_WORKLOGS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "EDIT_ALL_WORKLOGS"
},
{

	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "EDIT_OWN_WORKLOGS"
},
{



	"holder": {
	"type": "projectRole",
        "parameter": "10004"
	
      	},
	"permission": "WORK_ON_ISSUES"

}

],
 "name": "DevSecOps Project"


}'


}

main $1

